// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc3FMYCm4ofB_SlTU8q7xi0k8aieNMJck',
    appId: '1:583817390106:web:eee6049e0034e2ee0d49a3',
    messagingSenderId: '583817390106',
    projectId: 'kunalassingmentmishainfotech',
    authDomain: 'kunalassingmentmishainfotech.firebaseapp.com',
    databaseURL: 'https://kunalassingmentmishainfotech-default-rtdb.firebaseio.com',
    storageBucket: 'kunalassingmentmishainfotech.firebasestorage.app',
    measurementId: 'G-6PC4C3H20S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bJslgP1YbvH7RgaJ1-a0tec2fRSlFBU',
    appId: '1:583817390106:android:fac281e415fe69130d49a3',
    messagingSenderId: '583817390106',
    projectId: 'kunalassingmentmishainfotech',
    databaseURL: 'https://kunalassingmentmishainfotech-default-rtdb.firebaseio.com',
    storageBucket: 'kunalassingmentmishainfotech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8tjWR_b6ue2Ef95iQiLaGA4jxWuq8ow',
    appId: '1:583817390106:ios:5d8eac4ec9af46da0d49a3',
    messagingSenderId: '583817390106',
    projectId: 'kunalassingmentmishainfotech',
    databaseURL: 'https://kunalassingmentmishainfotech-default-rtdb.firebaseio.com',
    storageBucket: 'kunalassingmentmishainfotech.firebasestorage.app',
    iosBundleId: 'com.example.kunalAssignmentMishainfotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD8tjWR_b6ue2Ef95iQiLaGA4jxWuq8ow',
    appId: '1:583817390106:ios:5d8eac4ec9af46da0d49a3',
    messagingSenderId: '583817390106',
    projectId: 'kunalassingmentmishainfotech',
    databaseURL: 'https://kunalassingmentmishainfotech-default-rtdb.firebaseio.com',
    storageBucket: 'kunalassingmentmishainfotech.firebasestorage.app',
    iosBundleId: 'com.example.kunalAssignmentMishainfotech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc3FMYCm4ofB_SlTU8q7xi0k8aieNMJck',
    appId: '1:583817390106:web:2da2e46b15d30d920d49a3',
    messagingSenderId: '583817390106',
    projectId: 'kunalassingmentmishainfotech',
    authDomain: 'kunalassingmentmishainfotech.firebaseapp.com',
    databaseURL: 'https://kunalassingmentmishainfotech-default-rtdb.firebaseio.com',
    storageBucket: 'kunalassingmentmishainfotech.firebasestorage.app',
    measurementId: 'G-R4RPPNFZJC',
  );

}